### ISSUE TITLE
How to select a specific value of a Object in combo box ng model

### ISSUE THREAD

**Issue by ShoaibShahid** [Tinkoff/taiga-ui#1188]
I have use below combo box in my website. The flock list contains the array of objects and each object have certain properties.  It is working fine. Just when I select a option I want to be assign the ngModel a specific property of the object not the complete Object. If this is possible how can I do that? 

<tui-combo-box
              tuiTextfieldExampleText="Type a UID"
              [strict]='true'
              class="b-form"
              [stringify]="stringifyFlock"
              [(ngModel)]="selectedFlockId"
              (ngModelChange)='onSelectFlockChick($event)'
            >
              Flock
              <tui-data-list-wrapper
                *tuiDataList
                [items]="flocksList | tuiFilterByInputWith : stringifyFlock"
                [itemContent]="stringifyFlock | tuiStringifyContent"
              ></tui-data-list-wrapper>
            </tui-combo-box>
            
            readonly stringifyFlock = (item: {_id: string; flockUID: string}) =>
    `${item.flockUID}`;
    
    
    Thanks

**Comment by waterplea** [comment]
Hi @ShoaibShahid 

Please use `Discussions` tab for questions in future. 

I don't recommend doing that because you will make it harder on yourself since you would manage data and the way to display that data separately. Say your data is an object `{ id: number, name: string }`. If you put only `id` in the value of your form you would need to maintain certain infrastructure for a component to know how to display this `id`, instead of just having an object with all the info necessary and a pure function to display it, that knows everything from the object it received as input.

If you still want to go down that road, there are examples on the demo page showing you how you can achieve something like that:
https://taiga-ui.dev/components/select#id
https://taiga-ui.dev/components/multi-select#ids

It's pretty much the same for ComboBox.
