### ISSUE TITLE
🐞 - Postfix not positioned correctly with "text-align: right" on input-number

### ISSUE THREAD

**Issue by pwespi** [Tinkoff/taiga-ui#1193]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-apvc6b?file=src%2Fapp%2Fapp.component.html

### Description

When using `text-align: right` on a `tui-input-number` which has a postfix, the postfix is displayed on the left and moves while typing. I would expect the postfix to be displayed on the right of the number.

![image](https://user-images.githubusercontent.com/24232962/149355307-a2d71088-b2d1-47ee-a309-e0b1a05ca3ac.png)

PS: Thank you for this great library!

### Angular version

12.2.15 / 13.1.1

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [x] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hi @pwespi, thanks for bringing this up. However this is rather tricky to fix and in our internal design guidelines with text alignment to the right we put units in the label above, not in postfix, so that the right side of the number is aligned with other fields. In your case we would write it like `Type a weight, kg`. I'm not sure when we will be able to fix this because it's quite a big investment for not a lot of gain and therefore will be in the back of priority list, but maybe my suggestion would at least work for you for now.

**Comment by pwespi** [comment]
The behavior has changed, but now the postfix and the number are overlapping.

![Screenshot 2022-07-12 at 13 19 04](https://user-images.githubusercontent.com/24232962/178478248-1d97238b-9c98-4465-a6cf-05d848b5c75b.png)

https://stackblitz.com/edit/angular-bhn4qm

Taiga UI version: 2.53.0

**Comment by waterplea** [comment]
Works properly as of 3.0, on StackBlitz as well
