### ISSUE TITLE
🐞 - Sheet does not fix to bottom

### ISSUE THREAD

**Issue by rjlopezdev** [Tinkoff/taiga-ui#1269]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-mobile

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-xpqfnf?file=src/app/app.component.html

### Description

Sheet component does not fix to buttom if page has no content enough to scrolling.

### Angular version

12.2.4

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That's an issue with example stackblitz — `tui-root` is not stretched to the whole page. A fix would be to make it `min-height: 100%`. It's a bit tricky in the stackblitz example because there's a header outside `tui-root`, but it shouldn't be a problem in the real app where everything is inside `tui-root`. You just need to make sure app component has `display: block` and `min-height: 100%` and so are `html`, `body` and `tui-root`.

**Comment by waterplea** [comment]
Fixed with new `SheedDialog` in latest versions.
