### ISSUE TITLE
🚀 - Detect the end of scroll on Select/Multiselect/ComboBox

### ISSUE THREAD

**Issue by GrinJ** [Tinkoff/taiga-ui#1554]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Hello. 

Is it possible to detect when user is scrolling down the items in dropdown of Select/Multiselect/ComboBox (in tui-data-list or tui-data-list-wrapper) and subscribe to this event e.g. there are can be a lot of items to load from server and display them? So it seems logical to load data from server in parts and display them in parts too, so when user is scrolling down the load event is calling and new data appends to the end of the list?

**Comment by loxy** [comment]
You mean virtual scroll? See here for example: https://taiga-ui.dev/components/multi-select#virtual

It is based on the Angular CDK: https://material.angular.io/cdk/scrolling/overview

**Comment by waterplea** [comment]
Yes, you have 2 options - add scrollbar to the dropdown template yourself so that built-in dropdown scrolling does not happen or reach out for the `tui-scrollbar` through DOM API with some directive you can make. This is more like a question than a feature request — those are better suited for https://github.com/Tinkoff/taiga-ui/discussions
