### ISSUE TITLE
🐞 - Sorting chevron is facing the wrong direction

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#2265]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Is this issue blocking you?

Non-Blocking

### Description

When sorting in ascending order, the chevron points down, when sorting in descending order, the chevron points up.

Not sure if this is intentional, but the convention that I have seen is the chevron should point up for ascending, down for descending.

Some examples:
MUI: https://mui.com/x/react-data-grid/sorting/
AG-Grid: https://www.ag-grid.com/javascript-data-grid/row-sorting/
Postgres Admin:

![image](https://user-images.githubusercontent.com/197184/182510193-1014f8b6-fdd7-44f7-ac85-4b339f1d88e4.png)

### Angular version

14.0.0

### Taiga UI version

2.54.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like a one char fix here:
https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-table/components/table/th/th.template.html#L13

This confusion is caused by different proprietary icon in that place. @splincode we would need to do something about in in proprietary packages when this ticket is fixed.
