### ISSUE TITLE
InputDateTime format

### ISSUE THREAD

**Issue by hottabych1607** [Tinkoff/taiga-ui#229]
Hi, now when choosing a date and time, the date is formatted into an object
```
{
  "testValue": [
    "2017-03-15",
    {
      "hours": 11,
      "minutes": 11,
      "seconds": 0,
      "ms": 0
    }
  ]
}
```

Is it possible out of the box to manually set how the date should be formatted in an elegant way?
example: 2017-03-15T11:11:00

**Comment by waterplea** [comment]
Hello @hottabych1607!

Value is a tuple of `TuiDay` and `TuiTime`. There's no way to configure this behaviour, but both classes provide multiple ways to convert them, as well as be created with static method from strings and native `Date` objects.

**Comment by waterplea** [comment]
So under this issue let's implement the following feature:

Add token to format date and time so that there are two methods — from arbitrary T to TuiDay (TuiTime) and from TuiDay (TuiTime) to arbitrary T.

This way our controls will be able to support strings, native dates, date-fns, moment.js and whatever else people are using.
