### ISSUE TITLE
🐞 - ng add taiga-ui - old version (2.62.2)

### ISSUE THREAD

**Issue by Groxot** [Tinkoff/taiga-ui#2610]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Is this issue blocking you?

Non-Blocking

### Description

ng add taiga-ui install 2.62.2 but actial is 3

### Angular version

13

### Taiga UI version

?

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Probably, it happens because we've released 2.x. And it has `latest`-tag:

https://www.npmjs.com/package/@taiga-ui/cdk
<img width="777" alt="Screenshot 2022-09-06 at 15 10 17" src="https://user-images.githubusercontent.com/35179038/188631673-ab552735-a21b-409f-9736-305d34e54028.png">

**Expected condition:**
dont add `latest`-tag for 2.x
