### ISSUE TITLE
🐞 - `InputFlies` no text changes with new value of `TUI_INPUT_FILE_TEXTS` (i18n-token)

### ISSUE THREAD

**Issue by polinagorbunova** [Tinkoff/taiga-ui#2709]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-xncuqv

### Is this issue blocking you?

Blocking

### Description

При переопределении значения токена `TUI_INPUT_FILE_TEXTS ` на поток, который при смене локализации выдает новые значения текстов, значения `maxSizeRejectionReason` или `formatRejectionReason` в уже отрисованном rejectedFile не меняются на новые при динамической смене локализации

### Angular version

12.2.0

### Taiga UI version

2.62.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
**Minumum reproduction:**

1. Open https://taiga-ui.dev/components/input-files#single (with selected English language)
3. Drop **video**-file (not accepted format) to the drag-drop area.
4. Select another language via language switcher (for example,  "Portuguese")

**Expected behaviour:**
The error message is "Formato do arquivo inválido" (new selected language)

**Actual behaviour:**
The error message is still "Wrong file type" (/initial language).


https://user-images.githubusercontent.com/35179038/190373263-fd382b6b-6be1-4e36-8122-307729db0ee5.mov
