### ISSUE TITLE
🚀 - Allow more control over TuiFilesComponent display

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#2734]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

It's tricky customize the content of the files component, since it assumes there are 2 content elements (label and link). In the case where dragging occurs the only option for content is via the `texts` property.

I have the base display like so:

![image](https://user-images.githubusercontent.com/197184/191147007-61d1270f-8b03-41fa-88cf-ec942a84c326.png)

I would like to keep the same display on drag and change the background colour. However I can't do that because it computes the label while dragging as:

```
if (fileDragged) {
    return this.inputFileTexts$.pipe(
        map(texts => (multiple ? texts.dropMultiple : texts.drop)),
    );
}
```

**Comment by waterplea** [comment]
I think a good way to do this is to deprecate `link` and `label` inputs and just add single `content: PolymorpheusContent` input. Also adding a default values token, in which the current behavior will be the default component, that reads those deprecated inputs through DI. This would allow for all sorts of flexibility. PR is welcome if somebody wants to speed it up, since internally we do not really need it at this point so this is going to be low priority.

**Comment by oknimot** [comment]
Hey @waterplea, can I try to do this?

**Comment by waterplea** [comment]
> Hey @waterplea, can I try to do this?

Sure, go ahead 💪 I outlined my vision for it in a previous message.

**Comment by oknimot** [comment]
I think I'm done with this. @waterplea please check It out if it's according to your vision. I've tried to do it in the way you outlined 💪.
