### ISSUE TITLE
🐞 - @taiga-ui/addon-commerce - tui-input-card - [tuiTextfieldCustomContent] input does not works

### ISSUE THREAD

**Issue by avmaisak** [Tinkoff/taiga-ui#2752]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-commerce

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-card/API?tuiMode=null&tuiTextfieldCustomContent=Bell&tuiTextfieldCleaner=false

### Is this issue blocking you?

Non-Blocking

### Description

tui-input-card   - [tuiTextfieldCustomContent] input does not works

### Angular version

14.2.2

### Taiga UI version

3.3.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hello, @avmaisak. It does not supposed to work for input card because it is handled internally by payment system detection. If you want to override it with custom card icon, you can do it with `cardSrc` input. I suppose we should extend type to be `PolymorpheusContent` because now it says it only supports `string`, but in fact it would work for templates too. Does this solve your issue? If it's only about types, that should be a quick PR, you can even make it yourself and become a contributor. Hacktoberfest starts in a couple of days and it could be a good entry :)

**Comment by oknimot** [comment]
Hello, @waterplea I agree. I'm a newcomer in contributing to open-source, so I tried to implement this feature extending `cardSrc` type. Going to do Pull request, please check it out :)
