### ISSUE TITLE
🚀 - Add medium size support for InputPhoneInternational

### ISSUE THREAD

**Issue by vladzavadsky** [Tinkoff/taiga-ui#3256]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

I'd like to be able to use a component with `tuiTextfieldSize="m"` and `[tuiTextfieldLabelOutside]="true"`

**Comment by ddubrava** [comment]
Hi! Could you please provide how to support this? As I've spent an hour trying to figure out how it works and nothing helped ¯\_(ツ)_/¯

**Comment by waterplea** [comment]
Looks like it already supports different sizes, they are just no on the demo. You need to add `[tuiTextfieldSize]="size"` to `tui-input-phone-international` on demo page to see it in action. But country select needs some width adjustments. You can rely on `[data-size]` attribute for that. Also newly added `tuiTextfieldPrefix/Postfix` need to be added to that `tui-primitive-textfield` (`tuiTextfieldPrefix=""` and `tuiTextfieldPostfix=""`), otherwise if you set them on `tui-input-phone-international` you get them appearing in the select when it's focused.
