### ISSUE TITLE
🐞 - Unable to provide `NG_VALIDATORS` when component extends `AbstractTuiControl`

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#3433]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Is this issue blocking you?

Non-Blocking

### Description

Since `AbstractTuiControl` uses CVA approach when you set `valueAccessor` in the constructor we face the problem of providing `NG_VALIDATORS` because it provokes circular dependency injection. It's understandable why this is so but have you considered some variants to deal with this situation?

Here's an example of what I'm talking about https://blog.angular-university.io/angular-custom-form-controls/
the section about `How to implement nested form groups (an address nested form)`

### Angular version

14.2.7

### Taiga UI version

3.2.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You want the same component to provide `NG_VALIDATOR` and be `AbstractTuiControl`? We typically go around that by adding a directive with the same selector, it's also an interesting way to split codebase :) Would that work for you? I'm closing this issue because there's nothing we can do in Taiga UI, since `CONTROL_VALUE_ACCESSOR` is not enough and we need actual `NgControl` in our components. But feel free to continue discussing workarounds here.

**Comment by theorlovsky** [comment]
we might actually be able to use a directive, worth a try

**Comment by theorlovsky** [comment]
no, we're not 🙂
I'll provide you with an example later, maybe we'll figure out how to implement it in Taiga (and does it worth it)
