### ISSUE TITLE
🐞 - Why are dropdown styles recalculated?

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#3779]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

https://user-images.githubusercontent.com/12021443/222139325-9c83052e-fe10-42f2-bcb7-3a96cf9ee187.mov

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is expected. They are getting recalculated all the time, just values are the same so you don't see the updates. With complex cases like limited height due to screen edge or nested dropdowns some decimals probably do not add up to exactly the same number, even though Chrome probably trims it to max precision.

**Comment by waterplea** [comment]
Doesn't seem to be reproducible anymore.
