### ISSUE TITLE
🐞 - touch of tui-input trigger unnecessary zoom on iphone safari

### ISSUE THREAD

**Issue by LordOfTheMoon228** [Tinkoff/taiga-ui#3867]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

touch of tui-input trigger unnecessary zoom on iphone safari

### Angular version

12.2.13

### Taiga UI version

2.67.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by fed0rus** [comment]
Please fix this asap. This bug results in bad UX: web forms look wobbly, and focus on input in forms in popups result in unresponsive zooming of popup

**Comment by LordOfTheMoon228** [comment]
Can you give me an example, maybe screen or url, reproduction of this behavior?

**Comment by waterplea** [comment]
Unfortunately you can only fix that by disabling zoom through `head` `meta` tags. iOS zooms in on inputs with font size below 16px and this is not configurable.

**Comment by waterplea** [comment]
Ok, as a half measure we agreed with our designer to increase default font size (`var(--tui-font-text-m)`) from 15px to 16px, this would handle it for large inputs. Kind of like a breaking change, but hopefully shouldn't be too big of a deal since it's just 1px.

For the rest, the only way is the `head` tag:
https://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page

As far as I know, this does not disable user pinch zoom on latest iOS versions and Android doesn't have this issue. So if you are using smaller inputs, you might enable this fix by detecting that you are on iOS.
