### ISSUE TITLE
🐞 - Multiselect: Using pipe  inside *cdkVirtualFor directive causes dropdown to close after item is selected

### ISSUE THREAD

**Issue by vemikheevdev** [Tinkoff/taiga-ui#3943]
### Playground Link

https://stackblitz.com/edit/angular-36wbyv?file=src/app/app.component.html

### Description

I'm trying to implement multiselect with virtual scroll.
Using pipe for items (e.g. tuiHideSelected) inside *cdkVirtualFor directive causes dropdown to close after item is selected

https://stackblitz.com/edit/angular-ekdds2?file=src/app/app.component.html - basic select with pipe for elements - works great ✅
https://stackblitz.com/edit/angular-36wbyv?file=src/app/app.component.html - virtual scroll with pipe for elements - doesn't work ❌

### Angular version

12

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You shouldn't combine `tuiMultiSelectGroup` with `tuiHideSelected` otherwise your checkboxes are always unchecked :)

This happens for 3 reasons.

1. We use actual focus to navigation inside dropdowns, instead of `aria-activedescendant`. This makes some things easier, and some things harder. Biggest benefit is easy keyboard navigation and somewhat decent accessibility out of the box. In future, maybe in 4.0, we plan to move to `aria-activedescendant` but we need to build more expertise in accessibility first so that there's no detrimental effect. Besides it's a pretty huge refactor and we need to take into account DX and some form of backward compatibility and migration automation.
2. You are trying this in Chrome and Chrome is the only browser that emits `focusout` event when focused element is removed from DOM. There is no way to reliably tell this situation from manually calling `.blur()` on an element, as far as I'm aware. But we need to treat these cases differently, so...
3. We rely on Angular AnimationEngine that has a callback for elements about to be removed. However CDK virtual scroll removes elements manually, bypassing the engine, so our directives are not aware of that.

Here's how you can remedy that for your case:
```html
<cdk-virtual-scroll-viewport
  *tuiDataList
  tuiScrollable
  class="scroll"
  [itemSize]="44"
  (indexChange)="list.handleFocusLossIfNecessary()"
>
  <tui-data-list #list>
    <button
      *cdkVirtualFor="let item of countries | tuiHideSelected"
      tuiOption
      [value]="item"
      (click)="list.handleFocusLossIfNecessary()"
    >
      {{ item }}
    </button>
  </tui-data-list>
</cdk-virtual-scroll-viewport>
```

1. Add `#list` template reference value to `tui-data-list`.
2. Call `(click)="list.handleFocusLossIfNecessary()"` so that focus is returned to the `tui-multi-select` underlying input upon click, just before element is removed from DOM.
3. Note `(indexChange)="list.handleFocusLossIfNecessary()"` on `cdk-virtual-scroll-viewport` since it can also cause dropdown to close if by scrolling fast or any other case you get focused element removed from DOM due to virtualization.
