### ISSUE TITLE
🐞 - Low quality for pdf in preview

### ISSUE THREAD

**Issue by Parzisal** [Tinkoff/taiga-ui#4177]
### Playground Link

https://stackblitz.com/edit/angular-hrfyav?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

### Description

If you open it in the pdf preview component, then the quality breaks for them due to the INITIAL_SCALE_COEF, which is now 0.8
![1](https://user-images.githubusercontent.com/49144303/230921983-ab69b0c3-8485-4e1b-95ce-aeefb57d7a25.png)

### Angular version

14.3.0

### Taiga UI version

3.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
If you want to improve the quality of the PDF preview, you need to make it bigger initially and then scale with Taiga UI preview component. For example, you can set your `iframe` to be `300vh`/`300vw` in size, instead of `100`, then you would be able to zoom it and it would be crisp. However, we have a [dedicated service for PDFs](https://taiga-ui.dev/components/pdf-viewer) which I suggest you should switch to.
