### ISSUE TITLE
📚 - Update `Getting Started` page with standalone example

### ISSUE THREAD

**Issue by SerjMalko** [Tinkoff/taiga-ui#4766]
### Playground Link

//

### Description

Get error in console:

Assertion failed: EventPluginsModule must come after BrowserModule in imports

But, BrowserModule that doesn’t need to be explicitly imported when bootstrapping a Standalone Component.

### Angular version

16

### Taiga UI version

3.33

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Can you share your app bootstrap configuration?

**Comment by hakimio** [comment]
Are you importing providers from EventsPluginModule?
Check out this working standalone taiga-ui demo app: https://github.com/hakimio/ngx-ui-tour/tree/master/src

**Comment by SerjMalko** [comment]
`
bootstrapApplication(AppComponent, appConfig).catch((err) =>
  console.error(err)
);

... other file
export const appConfig: ApplicationConfig = {
    providers: [provideAnimations(), provideRouter(appRoutes, withEnabledBlockingInitialNavigation()), provideHttpClient()],
};
`

**Comment by waterplea** [comment]
> `bootstrapApplication(AppComponent, appConfig).catch((err) =>
>   console.error(err)
> );`
> 
> `export const appConfig: ApplicationConfig = {
>     providers: [provideAnimations(), provideRouter(appRoutes, withEnabledBlockingInitialNavigation()), provideHttpClient()],
> };`

What about tui-root, do you have `imports: [TuiRootModule]` inside your app component? It looks like it should be `imports: [TuiRootComponent]` there and add `importProvidersFrom(TuiRootModule)` to your bootstrap providers. Could you please try it? I guess it's a documentation issue rather than a bug and we should add standalone bootstrap config to the getting started. I believe `ng add taiga-ui` already does it properly.
