### ISSUE TITLE
[FEATURE] Angular update to active or LTS version

### ISSUE THREAD

**Issue by niklissad** [Tinkoff/taiga-ui#632]
# 🚀 Feature request

### Is your feature request related to a problem?

Installed Angular version in master branch is 9.1.12, but LTS is ended for this version (please check [here](https://angular.io/guide/releases#support-policy-and-schedule)) at Aug 06, 2021. This means that Angular 9 will not receive updates and fixes in the future

### Describe the solution you'd like

I suggest to update Angular version to active (12) or LTS (11)

### Describe alternatives you've considered

We have no alternatives because time cannot be stopped

**Comment by waterplea** [comment]
Taiga is dependant on internal projects. Until all of them are updated to a particular version, we cannot go up, otherwise they won't be compatible. It doesn't matter much, what version Taiga is built with since it's the app version that matters and Taiga can be ran on Angular 12 app fine. Updating to a version lower than 12 makes no sense, because 12 is the first one ivy for libraries was introduced. And it will not happen until the next major Taiga release anyway, since it's a breaking change. So I will close this issue for now, we will update in the next major release once internal apps update and once we gather enough pending breaking change to justify a major release.
