### ISSUE TITLE
[BUG] ManualHint - some directions are switched around

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#738]
# 🐞 Bug report

### Description

Following `tui hint` directions seem to be switched around:
- `top-left` and `top-right`
- `bottom-left` and `bottom-right`

When I choose `top-left` direction I expect the hint arrow to be on the left and the hint itself to be aligned to the left. Same for `bottom-left`.

**Comment by waterplea** [comment]
This is a direction to which the hint is displayed. top means it is positioned on top of the element and left means the cloud is on the left side of the arrow. This is by design.

**Comment by hakimio** [comment]
That's a very strange design then. Take a look at how [bootstrap popover top-left and top-right works](https://valor-software.com/ngx-bootstrap/#/popover#corner-placement) to see what's the expected behavior from user perspective.

**Comment by waterplea** [comment]
Think of it as a roll of cloth. You unwrap it to the top then to the left. Ultimately, it describes how hint looks rather than what edge of the host it is pointing to. I get that it might be confusing but it's a breaking change that is really not worth it since the required behavior can be already achieved. Maybe in 3.0 we can change it, but that would require 100+ devs on our side to relearn it :)

**Comment by waterplea** [comment]
Mentioned this in here https://github.com/TinkoffCreditSystems/taiga-ui/issues/739
Let's reimagine naming there with additional 4 directions.
